language: java
jdk: oraclejdk8
script: ./gradlew assemble test
sudo: required

before_install:
     - chmod +x gradlew

cache:
 directories:
  — $HOME/.gradle

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "50dde6503ca328fc8980e63252d3bd55e0d9b66f"
  file_glob: true
#  file: SmartTomcat*.jar
  file: build/libs/SmartTomcat*.jar
  on:
    tags: true
